steps:
  # build
  - id: "go build"
    name: golang:1.23
    entrypoint: /bin/bash
    args:
      - -c
      - |
        GO111MODULE=on GOOS=linux GOARCH=amd64 go build

  - id: 'docker build'
    name: 'gcr.io/cloud-builders/docker'
    waitFor: ['go build']
    env:
    - DOCKER_BUILDKIT=1
    args: [
      'build',
      '-f', 'Dockerfile',
      '-t', 'gcr.io/onx-daily/hydra-x:$SHORT_SHA',
      '-t', 'gcr.io/onx-staging/hydra-x:$SHORT_SHA',
      '-t', 'gcr.io/onx-production/hydra-x:$SHORT_SHA',
      '.'
    ]

  # push
  - id: 'docker push'
    name: 'gcr.io/cloud-builders/docker'
    waitFor: ['docker build']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "daily" ]]; then
          docker push gcr.io/onx-daily/hydra-x:$SHORT_SHA
        fi

        if [[ "$BRANCH_NAME" == "staging" ]]; then
          docker push gcr.io/onx-staging/hydra-x:$SHORT_SHA
        fi

        if [[ "$BRANCH_NAME" == "production" ]]; then
          docker push gcr.io/onx-production/hydra-x:$SHORT_SHA
        fi

        if [[ "$BRANCH_NAME" == "2.3.0" ]]; then
          docker push gcr.io/onx-daily/hydra-x:$SHORT_SHA
          docker push gcr.io/onx-staging/hydra-x:$SHORT_SHA
          docker push gcr.io/onx-production/hydra-x:$SHORT_SHA
        fi

tags:
  - hydrax